-- Добавление полей для детальной информации о машинах
-- Флаги и метаданные
ALTER TABLE cars ADD COLUMN IF NOT EXISTS has_details BOOLEAN DEFAULT FALSE;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS last_detail_update TIMESTAMP;

-- Дополнительные технические характеристики
ALTER TABLE cars ADD COLUMN IF NOT EXISTS power VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS torque VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS acceleration VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS max_speed VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS fuel_consumption VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS emission_standard VARCHAR(255);

-- Размеры и вес
ALTER TABLE cars ADD COLUMN IF NOT EXISTS length VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS width VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS height VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS wheelbase VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS curb_weight VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS gross_weight VARCHAR(255);

-- Двигатель и трансмиссия (для ДВС)
ALTER TABLE cars ADD COLUMN IF NOT EXISTS engine_type VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS engine_code VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS cylinder_count VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS valve_count VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS compression_ratio VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS turbo_type VARCHAR(255);

-- Электрические характеристики (для электромобилей)
ALTER TABLE cars ADD COLUMN IF NOT EXISTS battery_capacity VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS electric_range VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS charging_time VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS fast_charge_time VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS charge_port_type VARCHAR(255);

-- Трансмиссия и привод
ALTER TABLE cars ADD COLUMN IF NOT EXISTS transmission_type VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS gear_count VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS differential_type VARCHAR(255);

-- Подвеска и тормоза
ALTER TABLE cars ADD COLUMN IF NOT EXISTS front_suspension VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS rear_suspension VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS front_brakes VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS rear_brakes VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS brake_system VARCHAR(255);

-- Колеса и шины
ALTER TABLE cars ADD COLUMN IF NOT EXISTS wheel_size VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS tire_size VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS wheel_type VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS tire_type VARCHAR(255);

-- Безопасность
ALTER TABLE cars ADD COLUMN IF NOT EXISTS airbag_count VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS abs VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS esp VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS tcs VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS hill_assist VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS blind_spot_monitor VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS lane_departure VARCHAR(255);

-- Комфорт и удобство
ALTER TABLE cars ADD COLUMN IF NOT EXISTS air_conditioning VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS climate_control VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS seat_heating VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS seat_ventilation VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS seat_massage VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS steering_wheel_heating VARCHAR(255);

-- Мультимедиа и навигация
ALTER TABLE cars ADD COLUMN IF NOT EXISTS navigation VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS audio_system VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS speakers_count VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS bluetooth VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS usb VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS aux VARCHAR(255);

-- Освещение
ALTER TABLE cars ADD COLUMN IF NOT EXISTS headlight_type VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS fog_lights VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS led_lights VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS daytime_running VARCHAR(255);

-- История и состояние
ALTER TABLE cars ADD COLUMN IF NOT EXISTS owner_count INTEGER DEFAULT 0;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS accident_history TEXT;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS service_history TEXT;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS warranty_info TEXT;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS inspection_date VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS insurance_info TEXT;

-- Дополнительные детали
ALTER TABLE cars ADD COLUMN IF NOT EXISTS interior_color VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS exterior_color VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS upholstery VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS sunroof VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS panoramic_roof VARCHAR(255);

-- Дополнительные метаданные
ALTER TABLE cars ADD COLUMN IF NOT EXISTS view_count INTEGER DEFAULT 0;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS favorite_count INTEGER DEFAULT 0;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS contact_info TEXT;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS dealer_info TEXT;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS certification TEXT;

-- Карусель изображений
ALTER TABLE cars ADD COLUMN IF NOT EXISTS image_gallery TEXT;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS image_count INTEGER DEFAULT 0;

-- Дополнительные характеристики
ALTER TABLE cars ADD COLUMN IF NOT EXISTS seat_count VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS door_count VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS trunk_volume VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS fuel_tank_volume VARCHAR(255);

-- Создание индексов для часто используемых полей
CREATE INDEX IF NOT EXISTS idx_cars_has_details ON cars(has_details);
CREATE INDEX IF NOT EXISTS idx_cars_owner_count ON cars(owner_count);
CREATE INDEX IF NOT EXISTS idx_cars_view_count ON cars(view_count);
CREATE INDEX IF NOT EXISTS idx_cars_favorite_count ON cars(favorite_count);

