-- Дополнительные алиасы
WITH alias_values(name, orig_name, aliases) AS (
  VALUES
    ('Aian','埃安','Aian,埃安'),
    ('212','212','212,212'),
    ('Extremely krypton','极氪','Extremely krypton,极氪'),
    ('Dark blue car','深蓝汽车','Dark blue car,深蓝汽车'),
    ('smart','smart','smart,smart'),
    ('Gold Cup','金杯','Gold Cup,金杯'),
    ('ARCFOX Extreme Fox','ARCFOX极狐','ARCFOX Extreme Fox,ARCFOX极狐'),
    ('iCAR','iCAR','iCAR,iCAR'),
    ('Chase','大通','Chase,大通'),
    ('Fukuda','福田','Fukuda,福田'),
    ('Remote car','远程汽车','Remote car,远程汽车'),
    ('Aston Martin','阿斯顿·马丁','Aston Martin,阿斯顿·马丁'),
    ('Beijing Automobile Manufacturing Plant','北京汽车制造厂','Beijing Automobile Manufacturing Plant,北京汽车制造厂'),
    ('Iveco','依维柯','Iveco,依维柯'),
    ('Ferrari','法拉利','Ferrari,法拉利'),
    ('Chang''an Crossing','长安跨越','Chang''an Crossing,长安跨越'),
    ('Jianghuai Yttrium is','江淮钇为','Jianghuai Yttrium is,江淮钇为'),
    ('Jianghuai Ruifeng','江淮瑞风','Jianghuai Ruifeng,江淮瑞风'),
    ('Feifan Automobile','飞凡汽车','Feifan Automobile,飞凡汽车'),
    ('Alfa Romeo','阿尔法·罗密欧','Alfa Romeo,阿尔法·罗密欧'),
    ('Cheetah Cars','猎豹汽车','Cheetah Cars,猎豹汽车'),
    ('Beijing Automobile','北京汽车','Beijing Automobile,北京汽车'),
    ('Success Car','成功汽车','Success Car,成功汽车'),
    ('Dodge','道奇','Dodge,道奇'),
    ('Extremely more','极越','Extremely more,极越'),
    ('Siming','思铭','Siming,思铭'),
    ('SERES','SERES赛力斯','SERES,SERES赛力斯'),
    ('Dongfeng Yipai','东风奕派','Dongfeng Yipai,东风奕派'),
    ('Dongfeng Nano','东风纳米','Dongfeng Nano,东风纳米'),
    ('Dongfeng','东风','Dongfeng,东风'),
    ('Geely Geometry','吉利几何','Geely Geometry,吉利几何'),
    ('Zhidou','知豆','Zhidou,知豆'),
    ('China','中华','China,中华'),
    ('Lotus Sports Car','莲花跑车','Lotus Sports Car,莲花跑车'),
    ('Warrior','猛士','Warrior,猛士'),
    ('Yusheng','驭胜','Yusheng,驭胜'),
    ('Reading','雷丁','Reading,雷丁'),
    ('Qichen','启辰','Qichen,启辰'),
    ('Kairui','开瑞','Kairui,开瑞'),
    ('Guo Zhijun','国机智骏','Guo Zhijun,国机智骏'),
    ('Mahayana','大乘汽车','Mahayana,大乘汽车'),
    ('ZTE','中兴','ZTE,中兴'),
    ('Lamborghini','兰博基尼','Lamborghini,兰博基尼'),
    ('Na Zhijie','纳智捷','Na Zhijie,纳智捷'),
    ('southeast','东南','southeast,东南'),
    ('Rolls-Royce','劳斯莱斯','Rolls-Royce,劳斯莱斯'),
    ('SWM Sway Motors','SWM斯威汽车','SWM Sway Motors,SWM斯威汽车'),
    ('Enjoy the world','享界','Enjoy the world,享界'),
    ('Acura','讴歌','Acura,讴歌'),
    ('Yellow Sea','黄海','Yellow Sea,黄海'),
    ('Kowloon','九龙','Kowloon,九龙'),
    ('BAIC Magic Speed','北汽幻速','BAIC Magic Speed,北汽幻速'),
    ('Universiade','大运','Universiade,大运'),
    ('Jiangqi Group','江汽集团','Jiangqi Group,江汽集团'),
    ('Qoros','观致','Qoros,观致'),
    ('Brilliance New Day','华晨新日','Brilliance New Day,华晨新日'),
    ('Gao He','高合','Gao He,高合'),
    ('Ruiqi multi-function vehicle','锐骐多功能车','Ruiqi multi-function vehicle,锐骐多功能车'),
    ('NIO ES8','蔚来ES8','NIO ES8,蔚来ES8'),
    ('Extreme Krypton 001','极氪001','Extreme Krypton 001,极氪001'),
    ('Panamera','Panamera','Panamera,Panamera'),
    ('Hongguang MINIEV','宏光MINIEV','Hongguang MINIEV,宏光MINIEV'),
    ('Maybach S-class','迈巴赫S级','Maybach S-class,迈巴赫S级'),
    ('Nezha AYA','哪吒AYA','Nezha AYA,哪吒AYA'),
    ('Komick','柯米克','Komick,柯米克'),
    ('Xingrui','星瑞','Xingrui,星瑞'),
    ('Trumpchi M8','传祺M8','Trumpchi M8,传祺M8'),
    ('Lexus ES','雷克萨斯ES','Lexus ES,雷克萨斯ES'),
    ('Nezha U','哪吒U','Nezha U,哪吒U'),
    ('BMW 5 Series','宝马5系','BMW 5 Series,宝马5系'),
    ('Mercedes-Benz GLC','奔驰GLC','Mercedes-Benz GLC,奔驰GLC'),
    ('Ideal ONE','理想ONE','Ideal ONE,理想ONE'),
    ('Range Rover','揽胜','Range Rover,揽胜'),
    ('Hongqi HS5','红旗HS5','Hongqi HS5,红旗HS5'),
    ('Audi Q5L','奥迪Q5L','Audi Q5L,奥迪Q5L'),
    ('Xubao','旭豹','Xubao,旭豹'),
    ('NIO ES6','蔚来ES6','NIO ES6,蔚来ES6'),
    ('Baic Magic Speed S7','北汽幻速S7','Baic Magic Speed S7,北汽幻速S7'),
    ('Lynk Z10','领克Z10','Lynk Z10,领克Z10'),
    ('Euler good cat','欧拉好猫','Euler good cat,欧拉好猫'),
    ('Audi A6L','奥迪A6L','Audi A6L,奥迪A6L'),
    ('Regal','君威','Regal,君威'),
    ('Prado','普拉多','Prado,普拉多'),
    ('Flower fairy','花仙子','Flower fairy,花仙子'),
    ('Lingzhi','菱智','Lingzhi,菱智'),
    ('Haval Big Dog','哈弗大狗','Haval Big Dog,哈弗大狗'),
    ('Navigator (import)','航海家(进口)','Navigator (import),航海家(进口)'),
    ('Mercedes-Benz V-class','奔驰V级','Mercedes-Benz V-class,奔驰V级'),
    ('Portofino','Portofino','Portofino,Portofino'),
    ('Dongfeng Fengshen L7','东风风神L7','Dongfeng Fengshen L7,东风风神L7'),
    ('BMW X1','宝马X1','BMW X1,宝马X1'),
    ('Xiaomi SU7','小米SU7','Xiaomi SU7,小米SU7'),
    ('Jingyi X5','景逸X5','Jingyi X5,景逸X5'),
    ('Accord','雅阁','Accord,雅阁'),
    ('Changan UNI-Z','长安UNI-Z','Changan UNI-Z,长安UNI-Z'),
    ('AION','AION','AION,AION'),
    ('Tank 300','坦克300','Tank 300,坦克300'),
    ('Pentium T55','奔腾T55','Pentium T55,奔腾T55'),
    ('Beijing Hyundai ix25','北京现代ix25','Beijing Hyundai ix25,北京现代ix25'),
    ('RAV4 Rongfang','RAV4荣放','RAV4 Rongfang,RAV4荣放'),
    ('Haval H6','哈弗H6','Haval H6,哈弗H6'),
    ('Zhiji LS6','智己LS6','Zhiji LS6,智己LS6'),
    ('BMW X3','宝马X3','BMW X3,宝马X3'),
    ('Weilang','威朗','Weilang,威朗'),
    ('Octavia','明锐','Octavia,明锐'),
    ('Changan UNI-K','长安UNI-K','Changan UNI-K,长安UNI-K'),
    ('Xuan Yi','轩逸','Xuan Yi,轩逸'),
    ('Mercedes-Benz GLB','奔驰GLB','Mercedes-Benz GLB,奔驰GLB'),
    ('Songjiang New Energy','宋PLUS新能源','Songjiang New Energy,宋PLUS新能源'),
    ('golf','高尔夫','golf,高尔夫'),
    ('Emgrand','帝豪','Emgrand,帝豪'),
    ('Audi A3','奥迪A3','Audi A3,奥迪A3'),
    ('Name picture','名图','Name picture,名图'),
    ('SWM Swift X7','SWM斯威X7','SWM Swift X7,SWM斯威X7'),
    ('Jade','杰德','Jade,杰德'),
    ('BMW 1 Series','宝马1系','BMW 1 Series,宝马1系'),
    ('Qinhuangdao New Energy','秦Pro新能源','Qinhuangdao New Energy,秦Pro新能源'),
    ('Volvo S90','沃尔沃S90','Volvo S90,沃尔沃S90'),
    ('FJ','FJ','FJ,FJ'),
    ('BMW 3 Series','宝马3系','BMW 3 Series,宝马3系'),
    ('Civic','思域','Civic,思域'),
    ('Supermaster 4Runner','超霸4Runner','Supermaster 4Runner,超霸4Runner'),
    ('Mercedes-Benz GLA','奔驰GLA','Mercedes-Benz GLA,奔驰GLA'),
    ('Magotan','迈腾','Magotan,迈腾'),
    ('Han L','汉L','Han L,汉L'),
    ('Audi A8','奥迪A8','Audi A8,奥迪A8'),
    ('Bora','宝来','Bora,宝来'),
    ('Beiqi Changhe Q35','北汽昌河Q35','Beiqi Changhe Q35,北汽昌河Q35'),
    ('Angkola','昂科拉','Angkola,昂科拉'),
    ('Tanyue','探岳','Tanyue,探岳'),
    ('Camry','凯美瑞','Camry,凯美瑞'),
    ('Lantu Dreamer','岚图梦想家','Lantu Dreamer,岚图梦想家'),
    ('Mercedes-Benz G-class AMG','奔驰G级AMG','Mercedes-Benz G-class AMG,奔驰G级AMG'),
    ('Levante','Levante','Levante,Levante'),
    ('Porsche 718','保时捷718','Porsche 718,保时捷718'),
    ('Lexus NX','雷克萨斯NX','Lexus NX,雷克萨斯NX'),
    ('Model','Model','Model,Model'),
    ('KX','KX','KX,KX'),
    ('Asian dragon','亚洲龙','Asian dragon,亚洲龙'),
    ('Mercedes-Benz C-class','奔驰C级','Mercedes-Benz C-class,奔驰C级'),
    ('Chery Shu Xiangjia','奇瑞舒享家','Chery Shu Xiangjia,奇瑞舒享家'),
    ('Ideal L9','理想L9','Ideal L9,理想L9'),
    ('Dark blue S07','深蓝S07','Dark blue S07,深蓝S07'),
    ('BMW X5','宝马X5','BMW X5,宝马X5'),
    ('BMW 7 Series','宝马7系','BMW 7 Series,宝马7系'),
    ('Land Rover Defender','路虎卫士','Land Rover Defender,路虎卫士'),
    ('BMW X7','宝马X7','BMW X7,宝马X7'),
    ('Buick GL8','别克GL8','Buick GL8,别克GL8'),
    ('discover','发现','discover,发现'),
    ('Elfa','埃尔法','Elfa,埃尔法'),
    ('Range Rover Star Pulse','揽胜星脉','Range Rover Star Pulse,揽胜星脉'),
    ('Audi Q7','奥迪Q7','Audi Q7,奥迪Q7'),
    ('Trumpchi E8 New Energy','传祺E8新能源','Trumpchi E8 New Energy,传祺E8新能源'),
    ('Volvo S60','沃尔沃S60','Volvo S60,沃尔沃S60'),
    ('Mercedes-Benz C-class AMG','奔驰C级AMG','Mercedes-Benz C-class AMG,奔驰C级AMG'),
    ('Tiguan L','途观L','Tiguan L,途观L'),
    ('Lufeng X5','陆风X5','Lufeng X5,陆风X5'),
    ('MG6','MG6','MG6,MG6'),
    ('Mercedes-Benz E-class','奔驰E级','Mercedes-Benz E-class,奔驰E级'),
    ('AMG','AMG','AMG,AMG'),
    ('Lincoln MKX','林肯MKX','Lincoln MKX,林肯MKX'),
    ('Xiaopeng G7','小鹏G7','Xiaopeng G7,小鹏G7'),
    ('Ideal L7','理想L7','Ideal L7,理想L7'),
    ('BMW 6 Series GT','宝马6系GT','BMW 6 Series GT,宝马6系GT'),
    ('Mercedes-Benz G-class','奔驰G级','Mercedes-Benz G-class,奔驰G级'),
    ('Cadillac XT5','凯迪拉克XT5','Cadillac XT5,凯迪拉克XT5'),
    ('Audi RS','奥迪RS','Audi RS,奥迪RS'),
    ('BMW 5 Series (imported)','宝马5系(进口)','BMW 5 Series (imported),宝马5系(进口)'),
    ('Corolla','卡罗拉','Corolla,卡罗拉'),
    ('Tuyue','途岳','Tuyue,途岳'),
    ('FAW-Volkswagen CC','一汽-大众CC','FAW-Volkswagen CC,一汽-大众CC'),
    ('Audi A4L','奥迪A4L','Audi A4L,奥迪A4L'),
    ('Lynk 03','领克03','Lynk 03,领克03'),
    ('Euler Black Cat','欧拉黑猫','Euler Black Cat,欧拉黑猫'),
    ('century','世纪','century,世纪'),
    ('Xingyue L','星越L','Xingyue L,星越L'),
    ('BMW X4','宝马X4','BMW X4,宝马X4'),
    ('Cadillac CT5','凯迪拉克CT5','Cadillac CT5,凯迪拉克CT5'),
    ('Little ant','小蚂蚁','Little ant,小蚂蚁'),
    ('Beijing off-road BJ90','北京越野BJ90','Beijing off-road BJ90,北京越野BJ90'),
    ('Mazda 3','马自达3','Mazda 3,马自达3'),
    ('Weima EX5','威马EX5','Weima EX5,威马EX5'),
    ('Trumpchi E9','传祺E9','Trumpchi E9,传祺E9'),
    ('Song Pro','宋Pro','Song Pro,宋Pro'),
    ('Mercedes-Benz EQE','奔驰EQE','Mercedes-Benz EQE,奔驰EQE'),
    ('YARiS','YARiS','YARiS,YARiS'),
    ('Discover sports','发现运动','Discover sports,发现运动'),
    ('Teshun','特顺','Teshun,特顺'),
    ('Fox','福克斯','Fox,福克斯'),
    ('Changan UNI-T','长安UNI-T','Changan UNI-T,长安UNI-T'),
    ('Lynk 02','领克02','Lynk 02,领克02'),
    ('Touran','途安','Touran,途安'),
    ('Dongfeng Fengshen E70','东风风神E70','Dongfeng Fengshen E70,东风风神E70'),
    ('Seagull','海鸥','Seagull,海鸥'),
    ('Wilanda','威兰达','Wilanda,威兰达'),
    ('Toyota C-HR','丰田C-HR','Toyota C-HR,丰田C-HR'),
    ('Macan','Macan','Macan,Macan'),
    ('BMW 3 Series GT','宝马3系GT','BMW 3 Series GT,宝马3系GT'),
    ('Tiggo 5x','瑞虎5x','Tiggo 5x,瑞虎5x'),
    ('Beetle','甲壳虫','Beetle,甲壳虫'),
    ('Fit','飞度','Fit,飞度'),
    ('BMW 4 Series','宝马4系','BMW 4 Series,宝马4系'),
    ('Volvo XC60','沃尔沃XC60','Volvo XC60,沃尔沃XC60'),
    ('BMW X2','宝马X2','BMW X2,宝马X2'),
    ('Porsche 911','保时捷911','Porsche 911,保时捷911'),
    ('Tu Kai','途铠','Tu Kai,途铠'),
    ('Roewe e950','荣威e950','Roewe e950,荣威e950'),
    ('Changan UNI-V','长安UNI-V','Changan UNI-V,长安UNI-V'),
    ('Roewe i5','荣威i5','Roewe i5,荣威i5'),
    ('Xiaopeng P7','小鹏P7','Xiaopeng P7,小鹏P7'),
    ('Cadillac XT6','凯迪拉克XT6','Cadillac XT6,凯迪拉克XT6'),
    ('Trumpchi GS4','传祺GS4','Trumpchi GS4,传祺GS4'),
    ('Tuda','途达','Tuda,途达'),
    ('Kustu','库斯途','Kustu,库斯途'),
    ('Changan Qiyuan A05','长安启源A05','Changan Qiyuan A05,长安启源A05'),
    ('Range Rover Aurora','揽胜极光','Range Rover Aurora,揽胜极光'),
    ('Emgrand GL','帝豪GL','Emgrand GL,帝豪GL'),
    ('Teana','天籁','Teana,天籁'),
    ('Roewe i6 New Energy','荣威i6新能源','Roewe i6 New Energy,荣威i6新能源'),
    ('Han','汉','Han,汉'),
    ('Changan Auchan X5','长安欧尚X5','Changan Auchan X5,长安欧尚X5'),
    ('Explorer','探界者','Explorer,探界者'),
    ('Enjoy domain','享域','Enjoy domain,享域'),
    ('Audi Q2L','奥迪Q2L','Audi Q2L,奥迪Q2L'),
    ('Angke Flag','昂科旗','Angke Flag,昂科旗'),
    ('Roewe RX5','荣威RX5','Roewe RX5,荣威RX5'),
    ('Volvo XC90','沃尔沃XC90','Volvo XC90,沃尔沃XC90'),
    ('Pentium B70','奔腾B70','Pentium B70,奔腾B70'),
    ('Pajero (imported) V97','帕杰罗(进口)V97','Pajero (imported) V97,帕杰罗(进口)V97'),
    ('Destroyer 05','驱逐舰05','Destroyer 05,驱逐舰05'),
    ('Audi A6 (imported)','奥迪A6(进口)','Audi A6 (imported),奥迪A6(进口)'),
    ('Mercedes-Benz GLE Coupe','奔驰GLE轿跑','Mercedes-Benz GLE Coupe,奔驰GLE轿跑'),
    ('Ideal L6','理想L6','Ideal L6,理想L6'),
    ('Haval Raptors New Energy','哈弗猛龙新能源','Haval Raptors New Energy,哈弗猛龙新能源'),
    ('Sienna','赛那SIENNA','Sienna,赛那SIENNA'),
    ('Emgrand GS','帝豪GS','Emgrand GS,帝豪GS'),
    ('Roewe i6','荣威i6','Roewe i6,荣威i6'),
    ('Scenery 580','风光580','Scenery 580,风光580'),
    ('BMW 5 Series New Energy','宝马5系新能源','BMW 5 Series New Energy,宝马5系新能源'),
    ('Audi Q3','奥迪Q3','Audi Q3,奥迪Q3'),
    ('Qashqai','逍客','Qashqai,逍客'),
    ('Jaguar F-PACE','捷豹F-PACE','Jaguar F-PACE,捷豹F-PACE'),
    ('Binyue','缤越','Binyue,缤越'),
    ('Wuling Hongguang S3','五菱宏光S3','Wuling Hongguang S3,五菱宏光S3'),
    ('Yinglang','英朗','Yinglang,英朗'),
    ('Angkewei Plus','昂科威Plus','Angkewei Plus,昂科威Plus'),
    ('Lan Tu Zhiyin','岚图知音','Lan Tu Zhiyin,岚图知音'),
    ('Enjoy the world S9','享界S9','Enjoy the world S9,享界S9'),
    ('Lei Ling','雷凌','Lei Ling,雷凌'),
    ('GranTurismo','GranTurismo','GranTurismo,GranTurismo'),
    ('Lavida','朗逸','Lavida,朗逸'),
    ('Toyota bZ3','丰田bZ3','Toyota bZ3,丰田bZ3'),
    ('Tourang','途昂','Tourang,途昂'),
    ('Haval M6','哈弗M6','Haval M6,哈弗M6'),
    ('Golden Sea Lion M Classic','金海狮M经典','Golden Sea Lion M Classic,金海狮M经典'),
    ('Tank 400 New energy','坦克400新能源','Tank 400 New energy,坦克400新能源'),
    ('Jaguar XEL','捷豹XEL','Jaguar XEL,捷豹XEL'),
    ('Huracán','Huracán','Huracán,Huracán'),
    ('Vision X3','远景X3','Vision X3,远景X3'),
    ('Xiaopeng P7+','小鹏P7+','Xiaopeng P7+,小鹏P7+'),
    ('Sagitar','速腾','Sagitar,速腾'),
    ('BMW Z4','宝马Z4','BMW Z4,宝马Z4'),
    ('Qoros 3','观致3','Qoros 3,观致3'),
    ('Yingshipai','英仕派','Yingshipai,英仕派'),
    ('Lingdu','凌渡','Lingdu,凌渡'),
    ('Mercedes-Benz GLE','奔驰GLE','Mercedes-Benz GLE,奔驰GLE'),
    ('Vios FS','威驰FS','Vios FS,威驰FS'),
    ('Xiaomi YU7','小米YU7','Xiaomi YU7,小米YU7'),
    ('BMW X5 (imported)','宝马X5(进口)','BMW X5 (imported),宝马X5(进口)'),
    ('Cadillac CT4','凯迪拉克CT4','Cadillac CT4,凯迪拉克CT4'),
    ('cannon','炮','cannon,炮'),
    ('Cruze','科鲁泽','Cruze,科鲁泽'),
    ('dolphin','海豚','dolphin,海豚'),
    ('Cayenne New Energy','Cayenne新能源','Cayenne New Energy,Cayenne新能源'),
    ('Peugeot 408','标致408','Peugeot 408,标致408'),
    ('Ford F-150 Raptor','福特F-150猛禽','Ford F-150 Raptor,福特F-150猛禽'),
    ('Denza D9','腾势D9','Denza D9,腾势D9'),
    ('BYD F3','比亚迪F3','BYD F3,比亚迪F3'),
    ('Haval H9','哈弗H9','Haval H9,哈弗H9'),
    ('Audi S4','奥迪S4','Audi S4,奥迪S4'),
    ('Huasong','华颂','Huasong,华颂'),
    ('Mercedes-Benz S-class','Mercedes-Benz S-class','Mercedes-Benz S-class,Mercedes-Benz S-class'),
    ('Trumpchi GS3','Trumpchi GS3','Trumpchi GS3,Trumpchi GS3'),
    ('Cullinan','Cullinan','Cullinan,Cullinan'),
    ('Wisdom World S7','Wisdom World S7','Wisdom World S7,Wisdom World S7'),
    ('Xiaopeng G6','小鹏G6','Xiaopeng G6,小鹏G6'),
    ('Hongqi H9','红旗H9','Hongqi H9,红旗H9'),
    ('Tiggo 8','Tiggo 8','Tiggo 8,Tiggo 8'),
    ('Slightly blue 6','Slightly blue 6','Slightly blue 6,Slightly blue 6'),
    ('Mercedes-Benz CLA (imported)','Mercedes-Benz CLA (imported)','Mercedes-Benz CLA (imported),Mercedes-Benz CLA (imported)'),
    ('Passat','Passat','Passat,Passat'),
    ('Xiaopeng X9','Xiaopeng X9','Xiaopeng X9,Xiaopeng X9'),
    ('Grevia','Grevia','Grevia,Grevia'),
    ('smart Wizard#3','smart Wizard#3','smart Wizard#3,smart Wizard#3'),
    ('Wilfa','Wilfa','Wilfa,Wilfa'),
    ('Lexus LS','Lexus LS','Lexus LS,Lexus LS'),
    ('Land Cruiser (imported) LC71','Land Cruiser (imported) LC71','Land Cruiser (imported) LC71,Land Cruiser (imported) LC71'),
    ('Outlander','Outlander','Outlander,Outlander'),
    ('Mercedes-Benz GLS','Mercedes-Benz GLS','Mercedes-Benz GLS,Mercedes-Benz GLS'),
    ('Speed pie','Speed pie','Speed pie,Speed pie'),
    ('Blue Electric E5','Blue Electric E5','Blue Electric E5,Blue Electric E5'),
    ('Ghibli','Ghibli','Ghibli,Ghibli'),
    ('Jinke','Jinke','Jinke,Jinke'),
    ('McLaren','迈凯伦','McLaren,迈凯伦'),
    ('Pentium pony','Pentium pony','Pentium pony,Pentium pony'),
    ('Mercedes-Benz C-class (imported)','Mercedes-Benz C-class (imported)','Mercedes-Benz C-class (imported),Mercedes-Benz C-class (imported)'),
    ('Galaxy E8','Galaxy E8','Galaxy E8,Galaxy E8'),
    ('Avita 07','Avita 07','Avita 07,Avita 07'),
    ('MG5','MG5','MG5,MG5'),
    ('Cadillac XT4','Cadillac XT4','Cadillac XT4,Cadillac XT4'),
    ('Shadow Leopard','Shadow Leopard','Shadow Leopard,Shadow Leopard'),
    ('Brilliance New Day i03','Brilliance New Day i03','Brilliance New Day i03,Brilliance New Day i03'),
    ('Galaxy L6','Galaxy L6','Galaxy L6,Galaxy L6'),
    ('Kovoz','Kovoz','Kovoz,Kovoz'),
    ('Guide','Guide','Guide,Guide'),
    ('Sharp World','Sharp World','Sharp World,Sharp World'),
    ('GAC Toyota bZ4X','GAC Toyota bZ4X','GAC Toyota bZ4X,GAC Toyota bZ4X'),
    ('Mercedes-Benz A-class AMG (imported)','Mercedes-Benz A-class AMG (imported)','Mercedes-Benz A-class AMG (imported),Mercedes-Benz A-class AMG (imported)'),
    ('Santana','Santana','Santana,Santana'),
    ('Binzhi','Binzhi','Binzhi,Binzhi'),
    ('Trumpchi GS8','Trumpchi GS8','Trumpchi GS8,Trumpchi GS8'),
    ('Range Rover Sport','揽胜运动','Range Rover Sport,揽胜运动'),
    ('Nio ET5','蔚来ET5','Nio ET5,蔚来ET5'),
    ('Beijing off-road BJ40','北京越野BJ40','Beijing off-road BJ40,北京越野BJ40'),
    ('Jetta VS7','捷达VS7','Jetta VS7,捷达VS7'),
    ('Hao Ying','皓影','Hao Ying,皓影'),
    ('Damai X7','Damai X7','Damai X7,Damai X7'),
    ('TIIDA','TIIDA','TIIDA,TIIDA'),
    ('Wuling Zhiguang New Energy','五菱之光新能源','Wuling Zhiguang New Energy,五菱之光新能源'),
    ('Ask the world M9','Ask the world M9','Ask the world M9,Ask the world M9'),
    ('Lynk 06','领克06','Lynk 06,领克06'),
    ('Grecale','Grecale','Grecale,Grecale'),
    ('Binrui','Binrui','Binrui,Binrui'),
    ('Sea Lion 06','海狮06','Sea Lion 06,海狮06'),
    ('Jietu X70','捷途X70','Jietu X70,捷途X70'),
    ('Honda UR-V','Honda UR-V','Honda UR-V,Honda UR-V'),
    ('Vision X6','远景X6','Vision X6,远景X6'),
    ('Hanteng Motors','汉腾汽车','Hanteng Motors,汉腾汽车'),
    ('Vito','威霆','Vito,威霆'),
    ('Hongqi H9','红旗H9','Hongqi H9,红旗H9'),
    ('Yuan PLUS','元PLUS','Yuan PLUS,元PLUS'),
    ('Passat','帕萨特','Passat,帕萨特'),
    ('BMW i3','宝马i3','BMW i3,宝马i3'),
    ('Mercedes-Benz S-class','奔驰S级','Mercedes-Benz S-class,奔驰S级'),
    ('Mercedes-Benz E-Class (imported)','奔驰E级(进口)','Mercedes-Benz E-Class (imported),奔驰E级(进口)'),
    ('BMW X6','宝马X6','BMW X6,宝马X6'),
    ('Charon','夏朗','Charon,夏朗'),
    ('Style','型格','Style,型格'),
    ('Mercedes-Benz EQS','奔驰EQS','Mercedes-Benz EQS,奔驰EQS'),
    ('Changan CS75PLUS','长安CS75PLUS','Changan CS75PLUS,长安CS75PLUS'),
    ('Navigator','领航员','Navigator,领航员'),
    ('Baojun 360','宝骏360','Baojun 360,宝骏360'),
    ('Honda CR-V','本田CR-V','Honda CR-V,本田CR-V'),
    ('Wuling Rongguang V','五菱荣光V','Wuling Rongguang V,五菱荣光V'),
    ('Flying Home (imported)','飞行家(进口)','Flying Home (imported),飞行家(进口)'),
    ('Wuling Zhiguang New Energy','五菱之光新能源','Wuling Zhiguang New Energy,五菱之光新能源'),
    ('BMW 2 Series','宝马2系','BMW 2 Series,宝马2系'),
    ('Lord','领主','Lord,领主'),
    ('Lan Tu FREE','岚图FREE','Lan Tu FREE,岚图FREE'),
    ('Lanjing','揽境','Lanjing,揽境'),
    ('Zero run T03','零跑T03','Zero run T03,零跑T03'),
    ('Roewe RX3','荣威RX3','Roewe RX3,荣威RX3'),
    ('Vision X6','远景X6','Vision X6,远景X6'),
    ('Jietu X70','捷途X70','Jietu X70,捷途X70'),
    ('Cadillac CT6','凯迪拉克CT6','Cadillac CT6,凯迪拉克CT6'),
    ('Tiguan L New Energy','途观L新能源','Tiguan L New Energy,途观L新能源'),
    ('Land Cruiser (imported) LC300','兰德酷路泽(进口)LC300','Land Cruiser (imported) LC300,兰德酷路泽(进口)LC300'),
    ('Dark blue SL03','深蓝SL03','Dark blue SL03,深蓝SL03'),
    ('Smart running','智跑','Smart running,智跑'),
    ('Yi Ran','奕跑','Yi Ran,奕跑'),
    ('Hongqi E-QM5','红旗E-QM5','Hongqi E-QM5,红旗E-QM5'),
    ('Arrizo 8','艾瑞泽8','Arrizo 8,艾瑞泽8'),
    ('Hao Ying','皓影','Hao Ying,皓影'),
    ('Crown Lufang','皇冠陆放','Crown Lufang,皇冠陆放'),
    ('Lingxi L','灵悉L','Lingxi L,灵悉L'),
    ('Mercedes-Benz A-class (imported)','奔驰A级(进口)','Mercedes-Benz A-class (imported),奔驰A级(进口)'),
    ('Qiling T100','骐铃T100','Qiling T100,骐铃T100'),
    ('Cruze','科鲁兹','Cruze,科鲁兹'),
    ('Pentium T99','奔腾T99','Pentium T99,奔腾T99'),
    ('Binzhi','缤智','Binzhi,缤智'),
    ('KX3 proud run','KX3傲跑','KX3 proud run,KX3傲跑'),
    ('Mercedes-Benz A-class','奔驰A级','Mercedes-Benz A-class,奔驰A级'),
    ('Beijing Hyundai ix35','北京现代ix35','Beijing Hyundai ix35,北京现代ix35'),
    ('Mercedes-Benz CLA (imported)','奔驰CLA(进口)','Mercedes-Benz CLA (imported),奔驰CLA(进口)'),
    ('Boyue','博越','Boyue,博越'),
    ('Lynk 06','领克06','Lynk 06,领克06'),
    ('Sea Lion 06','海狮06','Sea Lion 06,海狮06'),
    ('Huiang','辉昂','Huiang,辉昂'),
    ('Grevia','格瑞维亚','Grevia,格瑞维亚'),
    ('Crown Road','冠道','Crown Road,冠道'),
    ('Extreme Krypton 009','极氪009','Extreme Krypton 009,极氪009'),
    ('Ask the world M5','问界M5','Ask the world M5,问界M5'),
    ('panda','熊猫','panda,熊猫'),
    ('Look up','仰望','Look up,仰望'),
    ('FAW','一汽','FAW,一汽'),
    ('Electric house','电动屋','Electric house,电动屋'),
    ('Love travel RV','爱旅房车','Love travel RV,爱旅房车'),
    ('Honda XR-V','Honda XR-V','Honda XR-V,Honda XR-V'),
    ('Versailles C5','Versailles C5','Versailles C5,Versailles C5'),
    ('Nio ET5T','Nio ET5T','Nio ET5T,Nio ET5T'),
    ('Jetta VS5','捷达VS5','Jetta VS5,捷达VS5'),
    ('Ferrari 488','Ferrari 488','Ferrari 488,Ferrari 488'),
    ('Zero run C11','Zero run C11','Zero run C11,Zero run C11'),
    ('Free light','Free light','Free light,Free light'),
    ('Elantra','Elantra','Elantra,Elantra'),
    ('Song MAX','Song MAX','Song MAX,Song MAX'),
    ('Highlander','Highlander','Highlander,Highlander'),
    ('Chrysler','克莱斯勒','Chrysler,克莱斯勒'),
    ('Qiling Automobile','骐铃汽车','Qiling Automobile,骐铃汽车'),
    ('Lingxi','灵悉','Lingxi,灵悉'),
    ('Baojun 510','宝骏510','Baojun 510,宝骏510'),
    ('Changan UNI-Z New Energy','长安UNI-Z新能源','Changan UNI-Z New Energy,长安UNI-Z新能源'),
    ('Xiaopeng MONA','小鹏MONA','Xiaopeng MONA,小鹏MONA'),
    ('Haoyue','Haoyue','Haoyue,Haoyue'),
    ('Weiran','Weiran','Weiran,Weiran'),
    ('Ideal L8','Ideal L8','Ideal L8,Ideal L8'),
    ('Gio Shuailing','Gio Shuailing','Gio Shuailing,Gio Shuailing'),
    ('Changan CS75','Changan CS75','Changan CS75,Changan CS75'),
    ('Corolla Sharp amplifier','Corolla Sharp amplifier','Corolla Sharp amplifier,Corolla Sharp amplifier'),
    ('Hongqi H5','红旗H5','Hongqi H5,红旗H5'),
    ('Giulia','Giulia','Giulia,Giulia'),
    ('Ask the world M7','Ask the world M7','Ask the world M7,Ask the world M7'),
    ('BMW iX1','BMW iX1','BMW iX1,BMW iX1'),
    ('Changan X5','Changan X5','Changan X5,Changan X5'),
    ('Nezha V','Nezha V','Nezha V,Nezha V'),
    ('Denza X','Denza X','Denza X,Denza X'),
    ('Ruicheng PLUS','Ruicheng PLUS','Ruicheng PLUS,Ruicheng PLUS'),
    ('Toure','Toure','Toure,Toure'),
    ('Lefu','Lefu','Lefu,Lefu'),
    ('Roewe RX5 New Energy','Roewe RX5 New Energy','Roewe RX5 New Energy,Roewe RX5 New Energy'),
    ('seal','seal','seal,seal'),
    ('Star Wish','Star Wish','Star Wish,Star Wish'),
    ('Ryoseki Motors','菱势汽车','Ryoseki Motors,菱势汽车'),
    ('Baic New Energy','Baic New Energy','Baic New Energy,Baic New Energy'),
    ('Cavan Motors','Cavan Motors','Cavan Motors,Cavan Motors'),
    ('Volkswagen ID.3','Volkswagen ID.3','Volkswagen ID.3,Volkswagen ID.3'),
    ('BYD e2','BYD e2','BYD e2,BYD e2'),
    ('Infiniti QX60','Infiniti QX60','Infiniti QX60,Infiniti QX60'),
    ('Roewe iMAX8','Roewe iMAX8','Roewe iMAX8,Roewe iMAX8'),
    ('LIFE','LIFE','LIFE,LIFE'),
    ('Winged Tiger','Winged Tiger','Winged Tiger,Winged Tiger'),
    ('Wuling Yangguang','五菱杨光','Wuling Yangguang,五菱杨光'),
    ('ID.4','ID.4','ID.4,ID.4'),
    ('Tang L','唐L','Tang L,唐L'),
    ('BYD F0','比亚迪F0','BYD F0,比亚迪F0'),
    ('Sharp Line','Sharp Line','Sharp Line,Sharp Line'),
    ('Lexus LX','雷克萨斯LX','Lexus LX,雷克萨斯LX'),
    ('Hechuang Automobile','合创汽车','Hechuang Automobile,合创汽车'),
    ('New Gio Motors','New Gio Motors','New Gio Motors,New Gio Motors'),
    ('summer','summer','summer,summer'),
    ('Ai Lishen','Ai Lishen','Ai Lishen,Ai Lishen'),
    ('Tiggo 7','Tiggo 7','Tiggo 7,Tiggo 7'),
    ('Jiajie','嘉际','Jiajie,嘉际'),
    ('Changan Qiyuan A07','长安启源A07','Changan Qiyuan A07,长安启源A07'),
    ('Qijun','奇骏','Qijun,奇骏'),
    ('Ford electric Horse','Ford electric Horse','Ford electric Horse,Ford electric Horse'),
    ('Polo','Polo','Polo,Polo'),
    ('Baojun 730','宝骏730','Baojun 730,宝骏730'),
    ('Odyssey','奥德赛','Odyssey,奥德赛'),
    ('Mazda CX-30','马自达CX-30','Mazda CX-30,马自达CX-30'),
    ('Xiaopeng G3','小鹏G3','Xiaopeng G3,小鹏G3')
)
UPDATE brands SET aliases = av.aliases
FROM alias_values av
WHERE (brands.name = av.name OR brands.orig_name = av.orig_name)
  AND (brands.aliases IS NULL OR brands.aliases = '');

INSERT INTO brands (name, orig_name, aliases, created_at, updated_at)
SELECT av.name, av.orig_name, av.aliases, NOW(), NOW()
FROM alias_values av
WHERE NOT EXISTS (
  SELECT 1 FROM brands b WHERE b.name = av.name OR b.orig_name = av.orig_name
);
