server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Health check endpoint
    location /health {
        alias /usr/share/nginx/html/health;
        try_files $uri =404;
        add_header Content-Type text/plain;
    }

    location /podbortg/ {
        alias /usr/share/nginx/html/podbortg/;
        try_files $uri $uri/ /podbortg/index.html;
    }
} 