server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location /podbortg/ {
        alias /usr/share/nginx/html/podbortg/;
        try_files $uri $uri/ /podbortg/index.html;
    }
} 